/**
 * generated by Scrooge 3.0.9
 */
package com.buzzinate.lezhi.thrift

import com.twitter.scrooge.ThriftEnum


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"), date = "2013-07-08T14:37:54.086+0800")
case object RecommendType {
  
  case object Insite extends RecommendType {
    val value = 0
    val name = "Insite"
  }
  
  case object Outsite extends RecommendType {
    val value = 1
    val name = "Outsite"
  }
  
  case object Trending extends RecommendType {
    val value = 2
    val name = "Trending"
  }
  
  case object Personalized extends RecommendType {
    val value = 3
    val name = "Personalized"
  }
  
  case object Itemcf extends RecommendType {
    val value = 4
    val name = "Itemcf"
  }

  /**
   * Find the enum by its integer value, as defined in the Thrift IDL.
   * @throws NoSuchElementException if the value is not found.
   */
  def apply(value: Int): RecommendType = {
    value match {
      case 0 => Insite
      case 1 => Outsite
      case 2 => Trending
      case 3 => Personalized
      case 4 => Itemcf
      case _ => throw new NoSuchElementException(value.toString)
    }
  }

  /**
   * Find the enum by its integer value, as defined in the Thrift IDL.
   * Returns None if the value is not found
   */
  def get(value: Int): Option[RecommendType] = {
    value match {
      case 0 => scala.Some(Insite)
      case 1 => scala.Some(Outsite)
      case 2 => scala.Some(Trending)
      case 3 => scala.Some(Personalized)
      case 4 => scala.Some(Itemcf)
      case _ => scala.None
    }
  }

  def valueOf(name: String): Option[RecommendType] = {
    name.toLowerCase match {
      case "insite" => scala.Some(RecommendType.Insite)
      case "outsite" => scala.Some(RecommendType.Outsite)
      case "trending" => scala.Some(RecommendType.Trending)
      case "personalized" => scala.Some(RecommendType.Personalized)
      case "itemcf" => scala.Some(RecommendType.Itemcf)
      case _ => scala.None
    }
  }
}



@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"), date = "2013-07-08T14:37:54.086+0800")
sealed trait RecommendType extends ThriftEnum with Serializable